export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCELIST = 'SET_SEQUENCELIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENTINDEX = 'SET_CURRENTINDEX'

export const SET_CURRENTSONG = 'SET_CURRENTSONG'

export const SET_DISC_LIST = 'SET_DISC_LIST'

export const SET_TOP_LIST = 'SET_TOP_LIST'
